Release phase1
Star-Academy/Winter1402-TwoWeek-InternShip-Frontend pull request #6
Opened 2023-12-28 16:28 UTC by At1X

phase 1 released

2023-12-30 08:08 UTC, milar7 requested changes

2023-12-30 08:08 UTC, milar7 commented on src/styles.scss
> +  width: 0.4rem;
توصیه میشه واسه تجربه بهتر کاربری هیچ وقت اسکرولبار رو تغییر ندید. یسری دلایل داره مثلا اینکه داخل همه مروگر ها یکسان نیست دیگه. الان همینی که زدید داخل firefox اعمال نمیشه

2023-12-30 08:08 UTC, milar7 commented on src/styles.scss
> +$primary-color: #18181c;
از hsl استفاده کنید بجای hex. 
https://elad.medium.com/why-css-hsl-colors-are-better-83b1e0b6eead

بقیه جاها هم تغییر بدین

2023-12-30 08:08 UTC, milar7 commented on src/app/app.component.html
> +        <img src="assets/images/epic-logo.svg" alt="epic games logo" width="35" height="35">
بهتره واسه عکس ها از فرمت
webP
که واسه وب بهینه شده استفاده کنید.
از این سایت میتونید کمک بگیرید
https://squoosh.app/

https://star-academy.github.io/codestar-documents/docs/frontend/phase02-pilot#%D8%B9%DA%A9%D8%B3%D9%87%D8%A7

2023-12-30 08:08 UTC, milar7 commented on src/styles.scss
> +.main-body {
یه مقدار max-width در نظر بگیرید تا در صفحه نمایش های 4k و بالاتر هم قابل استفاده باشه وبسایت

2023-12-30 08:08 UTC, milar7 commented on src/app/app.component.scss
> +    font-size: $global-font-size;
add one line space after this line

2023-12-30 08:08 UTC, milar7 commented on src/app/app.component.scss
> +  color: black;
hsl

2023-12-30 08:08 UTC, milar7 commented on src/app/app.component.scss
> +  .banner {
هر جا که indent دارید قبلش یه enter بزارید

2023-12-30 08:08 UTC, milar7 commented on src/app/app.component.scss
> +        right: 1rem;
به جای
left or right or ,,,
 از
Logical Properties
استفاده کنید.
لینک:
https://star-academy.github.io/codestar-documents/docs/frontend/phase06-clean-code#logical-properties

2023-12-30 08:08 UTC, milar7 commented on src/app/app.component.scss
> +        //visibility: hidden;
remove comments

2023-12-30 08:08 UTC, milar7 commented on src/app/app.component.scss
> +        margin-left: 1.5rem;
logical properties

2024-01-01 19:55 UTC, At1X commented on src/styles.scss
> +.main-body {
سلام. ما متوجه نشدیم کجا و دقیقا به چه علتی باید از max-width استفاده کنیم.

2024-01-02 05:52 UTC, milar7 commented on src/styles.scss
> +.main-body {
معمولا میان یک مقدار max-width واسه بالاترین المان wrapper وبسایت در نظر میگیرن تا وبسایت در صفحه نمایش های خیلی عریض هم بخوبی قابل استفاده باشه. البته خیلی به دیزاین و طراحی اولیه سایت هم بستگی داره. یعنی ممکنه بعضی طراحی‌ها نیازی نداشته باشن.
بهتره با dev-tools برید رو حالت ریسپانسیو و یک رزلوشن خیلی عریض انتخاب کنید. اگه دیدید المان‌های سایت خیلی از هم جدا شدن و استفاده ازشون سخت شد،‌بهتره یه max-width واسه اون قسمت یا ساده تر به کل وبسایت در نظر بگیرید

2024-01-02 05:53 UTC, milar7 approved these changes

2024-01-07 09:16 UTC, merged